apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoice-api
  template:
    metadata:
      labels:
        app: invoice-api
    spec:
      containers:
      - name: api
        image: 899752570521.dkr.ecr.eu-west-3.amazonaws.com/invoice-api:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
